### Question 1 (b)

In [12]:
import numpy as np
from utils import generate_data

np.random.seed(0)

# Generate data X1
N = 1000
mean = np.array([0, 0, 0])
cov = np.diag([3, 5, 2])
X1 = generate_data(mean, cov, N)


In [ ]:
mu_hat_ml_full = np.mean(X1, axis=0)
Sigma_hat_ml_full = np.cov(X1, rowvar=False, bias=True) 

print("\nPart (b) - Full MLE Estimates for C1")
print("Mean Vector:\n", mu_hat_ml_full)
print("Covariance Matrix:\n", Sigma_hat_ml_full)



Part (b) - Full MLE Estimates for C1
Mean Vector:
 [-0.06052505 -0.01056471 -0.06109331]
Covariance Matrix:
 [[ 2.95760961 -0.0620756  -0.03027466]
 [-0.0620756   4.4889776  -0.04684385]
 [-0.03027466 -0.04684385  1.87998026]]
