### Question 1 (e)

In [4]:
import numpy as np
from utils import generate_data

np.random.seed(0)

# Generate data X2
N = 1000
mean = np.array([1, 5, -3])
cov = np.array([[1, 0, 0], [0, 4, 1], [0, 1, 6]])
X2 = generate_data(mean, cov, N)


In [5]:
mu_hat_ml_full = np.mean(X2, axis=0)
Sigma_hat_ml_full = np.cov(X2, rowvar=False, bias=True)  # bias=True => MLE (divide by N)

print("\nPart (e) - Full MLE Estimates for C1")
print("Mean Vector:\n", mu_hat_ml_full)
print("Covariance Matrix:\n", Sigma_hat_ml_full)



Part (e) - Full MLE Estimates for C1
Mean Vector:
 [ 0.9568005   4.93428697 -2.98573253]
Covariance Matrix:
 [[ 0.93999013 -0.03597977 -0.02570444]
 [-0.03597977  3.80639465  0.73178468]
 [-0.02570444  0.73178468  5.48737635]]
